#!/bin/bash

# remove previous binanry file
rm AlchitryCuAlchitryIo_bitmap.bin

# copy new binanry file
cp //home/schanen/DetectionSynchrone/AlchitryCu/AlchitryCu_Implmnt/sbt/outputs/bitmap/AlchitryCuAlchitryIo_bitmap.bin AlchitryCuAlchitryIo_bitmap.bin

# load current binary
iceprog AlchitryCuAlchitryIo_bitmap.bin
